"""Shared utilities for the amir deterministic tooling.

Stdlib only, plus defensive imports of pyyaml/jsonschema via require_yaml()/require_jsonschema().
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

PIP_HINT = (
    "Missing required Python package(s). Install them with:\n"
    "    python -m pip install pyyaml jsonschema\n"
)

GENERATED_HEADER = "generated by amirctl; do not edit; regenerate via /amir:repair_project"
GENERATED_HEADER_MD = f"<!-- {GENERATED_HEADER} -->"
GENERATED_MARKER_KEY = "//amir-generated"

TOOLS_DIR = Path(__file__).resolve().parent

_COMMENT_STYLES = {
    ".md": ("<!-- ", " -->"),
    ".mdc": ("<!-- ", " -->"),
    ".py": ("# ", ""),
    ".ps1": ("# ", ""),
    ".sh": ("# ", ""),
    ".yaml": ("# ", ""),
    ".yml": ("# ", ""),
    ".toml": ("# ", ""),
    ".js": ("// ", ""),
    ".mjs": ("// ", ""),
    ".cjs": ("// ", ""),
    ".ts": ("// ", ""),
}


class AmirError(Exception):
    """Raised for expected, user-facing failures."""


def require_yaml():
    try:
        import yaml  # noqa: PLC0415
    except ImportError as exc:  # pragma: no cover - environment dependent
        raise SystemExit(f"ERROR: PyYAML is not installed ({exc}).\n{PIP_HINT}")
    return yaml


def require_jsonschema():
    try:
        import jsonschema  # noqa: PLC0415
    except ImportError as exc:  # pragma: no cover - environment dependent
        raise SystemExit(f"ERROR: jsonschema is not installed ({exc}).\n{PIP_HINT}")
    return jsonschema


def default_catalog_root() -> Path:
    """The marketplace repo root; tools live at <root>/plugins/amir_system/tools."""
    return TOOLS_DIR.parent.parent.parent


def find_project_root(start: Path | None = None, explicit: str | None = None) -> Path | None:
    """Nearest ancestor (of cwd or start) containing .amir/project.yaml, or --project override."""
    if explicit:
        root = Path(explicit).resolve()
        if not (root / ".amir" / "project.yaml").is_file():
            raise AmirError(f"no .amir/project.yaml found under --project path: {root}")
        return root
    current = Path(start).resolve() if start else Path.cwd().resolve()
    for candidate in (current, *current.parents):
        if (candidate / ".amir" / "project.yaml").is_file():
            return candidate
    return None


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 16), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise AmirError(f"file not found: {path}")
    except json.JSONDecodeError as exc:
        raise AmirError(f"invalid JSON in {path}: line {exc.lineno} column {exc.colno}: {exc.msg}")


def dump_json(data) -> str:
    """Deterministic JSON serialization (sorted keys, trailing newline)."""
    return json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def comment_header_for(path: Path) -> str | None:
    style = _COMMENT_STYLES.get(path.suffix.lower())
    if style is None:
        return None
    prefix, suffix = style
    return f"{prefix}{GENERATED_HEADER}{suffix}"


def inject_generated_header(text: str, path: Path) -> str:
    """Insert the generated-file header without breaking YAML frontmatter."""
    header = comment_header_for(path)
    if header is None or GENERATED_HEADER in text:
        return text
    if path.suffix.lower() in (".md", ".mdc") and text.startswith("---"):
        lines = text.split("\n")
        for index in range(1, len(lines)):
            if lines[index].strip() in ("---", "..."):
                return "\n".join(lines[: index + 1] + [header] + lines[index + 1 :])
    return f"{header}\n{text}"


def is_amir_generated_text(path: Path) -> bool:
    """Ownership check: only files carrying the generated header are ours to delete."""
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:2048]
    except OSError:
        return False
    return GENERATED_HEADER in head
